### PR TITLE
Change IteratorSize on EnumerableMap to just pass through from underl…

### PR DESCRIPTION
**Pull request by quinnj**
…ying iterator

In a benchmark I'm running this made about a 10% impact on performance; the problem is that the current code is non-compile-time inferrable, so it involved doing runtime dispatch on a trait meant to be compile-time friendly.

### CODE REVIEW

**Comment by davidanthoff** [comment]
On one hand this looks fine, but on the other hand I'm worried that I probably introduced the more elaborate thing for some reason. Of course, now I can't remember/think of one...

We could probably get the same semantics as the old version but without the perf problems by using a generated function?

**Comment by quinnj** [comment]
Most of the other definitions of `IteratorSize` in QueryOperators are like:
```julia
(Base.IteratorSize(S) isa Base.HasLength || Base.IteratorSize(S) isa Base.HasShape) ? Base.HasLength() : Base.SizeUnknown()
```
so I wonder if you were going for a similar type thing here? Using the above definition would be much better, since it's inferrable.

**Comment by quinnj** [comment]
Oh, another quick question while we're here: any reason we don't declare `IteratorInterfaceExtensions.isiterable(::Enumerable*)` in this package? Would you be open to a PR adding those definitions? It cleans up codegen and avoids the `applicable` call (even though it's relatively negligible compared to everything else).

**Comment by davidanthoff** [comment]
Yes, I think the two `IteratorSize` things are equivalent, right? I'm pretty sure there is no deeper reason that I've used a different formulation for the `map` case, and if the other formulation works better with the compiler, then lets go with that!

And yes, adding a `isiterable` for `Enumerable` also seems like a good idea.

**Comment by nalimilan** [comment]
Have you also tried `Base.IteratorSize(S) isa Union{Base.HasLength, Base.HasShape}`? Might save one call.

**Comment by davidanthoff** [comment]
@quinnj let me know if you want to try @nalimilan's suggestion or just merge this right away!

**Comment by quinnj** [comment]
Updated.

**Pull request merged**
